---
language: ruby
cache: bundler

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

env:
  - CHEF-VERSION=11
  - CHEF_VERSION=12
  - CHEF_VERSION=13
  - CHEF_VERSION=14
  - CHEF_VERSION=

script: true
