---
language: ruby
cache: bundler

env:
  - CHEF_VERSION=
  - CHEF-VERSION=14
  - CHEF_VERSION=13
  - CHEF_VERSION=12
  - CHEF_VERSION=11

rvm:
  - ruby-head
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - 1.9

script: chef-client --version
